# Loading data set

In [389]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\New folder (3)\book-recommender\dataset\Book_Details.csv")
df

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,1,2,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Order of the Phoenix,Harry Potter is about to start his fifth year ...,"['912 pages, Paperback']","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,2,3,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Sorcerer's Stone,Harry Potter has no idea how famous he is. Tha...,"['309 pages, Hardcover']","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,3,5,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Prisoner of Azkaban,"Harry Potter, along with his best friends, Ron...","['435 pages, Mass Market Paperback']","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,4,6,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Goblet of Fire,It is the summer holidays and soon Harry Potte...,"['734 pages, Paperback']","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,16220,208877606,https://images-na.ssl-images-amazon.com/images...,Finistère,The 1920s. When wealthy American adolescent Ma...,"['316 pages, Paperback']","['First published January 1, 1951']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['316'],"['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1..."
16221,16221,208877648,https://images-na.ssl-images-amazon.com/images...,The Descent,"Set in the 1950s, The Descent asks the questio...","['268 pages, Paperback']","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,16222,209251042,https://images-na.ssl-images-amazon.com/images...,FDR Unmasked: 73 Years of Medical Cover-ups Th...,THE HIDDEN ILLNESSES THAT SHAPED FDR’S LIFE AN...,"['316 pages, Paperback']","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,16223,209441121,https://images-na.ssl-images-amazon.com/images...,Code Yellow in Gretna Green,"In Gateway terminology, a ""Code Yellow"" signif...","['776 pages, Kindle Edition']","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [390]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16225 entries, 0 to 16224
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           16225 non-null  int64
 1   book_id              16225 non-null  int64
 2   cover_image_uri      16225 non-null  str
 3   book_title           16225 non-null  str
 4   book_details         16177 non-null  str
 5   format               16225 non-null  str
 6   publication_info     16225 non-null  str
 7   authorlink           16225 non-null  str
 8   author               16225 non-null  str
 9   num_pages            16225 non-null  str
 10  genres               16225 non-null  str
 11  num_ratings          16225 non-null  int64
 12  num_reviews          16225 non-null  int64
 13  average_rating       16225 non-null  float64
 14  rating_distribution  16225 non-null  str
dtypes: float64(1), int64(4), str(10)
memory usage: 22.3 MB

In [391]:
df.columns

Index(['Unnamed: 0', 'book_id', 'cover_image_uri', 'book_title',
       'book_details', 'format', 'publication_info', 'authorlink', 'author',
       'num_pages', 'genres', 'num_ratings', 'num_reviews', 'average_rating',
       'rating_distribution'],
      dtype='str')

In [392]:
df.drop(columns=['Unnamed: 0', 'book_id', 'cover_image_uri', 
        'format', 'publication_info', 'authorlink','num_pages',
        'num_ratings', 'num_reviews', 'average_rating',
        'rating_distribution'],inplace=True)

In [393]:
df.columns

Index(['book_title', 'book_details', 'author', 'genres'], dtype='str')

In [394]:
import re
import nltk
import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()


def preprocess_text(text):

    if pd.isna(text):
        return ""

    # lowercase
    text = text.lower()

    # remove punctuation/numbers
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # tokenize
    words = text.split()

    # remove stopwords + lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)


df['book_details'] = df['book_details'].apply(preprocess_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Alvi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Alvi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Alvi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [395]:
df['genres'][0]

"['Fantasy', 'Young Adult', 'Fiction', 'Magic', 'Childrens', 'Audiobook', 'Adventure']"

In [396]:
import ast

def process_genres(x):
    if pd.isna(x):
        return ""
    
    if isinstance(x, list):
        return " ".join(x)
    
    try:
        x = ast.literal_eval(x)
        return " ".join(x) if isinstance(x, list) else str(x)
    except:
        return str(x)

df['genres'] = df['genres'].apply(process_genres)

In [397]:
df['genres'][0]

'Fantasy Young Adult Fiction Magic Childrens Audiobook Adventure'

In [398]:
df['tags'] = (
    (df['author'].fillna(' ') + ' ') * 4 +
    (df['book_title'].fillna(' ') + ' ') * 3 +
    (df['genres'].fillna(' ') + ' ') * 2 +
    (df['book_details'].fillna(' ') + ' ')
)

In [399]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1, 2),
    max_features=10000
)

matrix = tfidf.fit_transform(df['tags'])

print(matrix.shape)

(16225, 10000)

In [400]:
# from sklearn.metrics.pairwise import cosine_similarity

# similarity_matrix = cosine_similarity(matrix)

from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(n_neighbors=21, metric='cosine')
knn.fit(matrix)

distances, indices = knn.kneighbors(matrix)

similarity_indices = indices[:, 1:]
similarity_scores = 1 - distances[:, 1:]

In [401]:
def recommend_books(book_title, n=10):

    matches = df.index[
        df['book_title']
        .fillna('')
        .str.lower()
        .eq(book_title.lower())
    ].tolist()

    if not matches:
        return pd.DataFrame()

    book_index = matches[0]

    indices = similarity_indices[book_index][:n]
    scores = similarity_scores[book_index][:n]

    result = df.iloc[indices][
        ['book_title', 'author', 'genres']
    ].copy()

    result['similarity'] = scores

    return result

In [402]:
recommend_books('The Midnight Library')

,book_title,author,genres,similarity
15607,The Midnight Library,Matt Haig,Fiction Fantasy Contemporary Audiobook Magical...,0.845421
14854,The Library Book,Susan Orlean,Nonfiction History Books About Books Audiobook...,0.360132
14132,The Library at Mount Char,Scott Hawkins,Fantasy Horror Fiction Science Fiction Adult M...,0.260832
14040,Reasons to Stay Alive,Matt Haig,Nonfiction Mental Health Self Help Memoir Psyc...,0.255089
12955,The Humans,Matt Haig,Fiction Science Fiction Fantasy Humor Contempo...,0.247720
15621,The Woman in the Library,Sulari Gentill,Mystery Fiction Thriller Mystery Thriller Audi...,0.236356
372,Genome: The Autobiography of a Species in 23 C...,Matt Ridley,Science Nonfiction Biology Genetics Evolution ...,0.225707
12893,Escape from Mr. Lemoncello's Library,Chris Grabenstein,Middle Grade Mystery Fiction Childrens Adventu...,0.221407
1210,The House of the Scorpion,Nancy Farmer,Young Adult Science Fiction Dystopia Fiction F...,0.209624
1319,Midnight’s Children,Salman Rushdie,Fiction Magical Realism Classics India Histori...,0.208019

In [403]:
recommend_books("Twisted Love", 10)

,book_title,author,genres,similarity
15851,Twisted Lies,Ana Huang,Romance Contemporary Contemporary Romance Adul...,0.240753
14068,Twisted,Anna Gallegos,Horror,0.228103
15568,Twisted Love,Ana Huang,Romance Contemporary Contemporary Romance New ...,0.225498
15616,Twisted Hate,Ana Huang,Romance Contemporary Contemporary Romance New ...,0.181285
15613,Twisted Games,Ana Huang,Romance Contemporary Contemporary Romance Audi...,0.179187
13627,Twisted,Lola Smirnova,Dark Thriller Suspense Fiction Adult Realistic...,0.167405
14674,Raincheck,Marlo Lanz,Romance Mystery Romantic Fiction Thriller Adve...,0.163738
13835,Eeny Meeny,M.J. Arlidge,Thriller Crime Mystery Fiction Mystery Thrille...,0.152617
15029,All Your Twisted Secrets,Diana Urban,Mystery Young Adult Thriller Mystery Thriller ...,0.150334
13096,High Tide,Inga Ābele,Fiction Mystery Contemporary Literary Fiction ...,0.147745

In [404]:
import pickle

with open('book_similarity.pkl', 'wb') as f:
    pickle.dump(
        {
            'indices': similarity_indices,
            'scores': similarity_scores
        },
        f
    )